name: CI

on: [push , pull_request]

jobs:
  checkout_source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  install_dependencies:
    runs-on: ubuntu-latest
    needs: checkout_source
    steps:

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Install dependencies
        run: |
          npm install
          npm run cp-ci-env
